# Generated by Django 5.2.16 on 2026-07-25 06:58

import caregivers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0002_streakrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=caregivers.models._generate_invite_code, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=caregivers.models._default_expiry)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'caregiver')},
            },
        ),
        migrations.CreateModel(
            name='CaregiverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_snapshot', models.TextField()),
                ('channel', models.CharField(choices=[('dashboard', 'Dashboard'), ('push', 'Push')], default='dashboard', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='caregivers.caregiverlink')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_notifications', to='checkins.moodcheckin')),
            ],
            options={
                'unique_together': {('checkin', 'caregiver_link')},
            },
        ),
    ]
