# Generated by Django 5.2.16 on 2026-07-25 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('recovery_start_date', models.DateField(blank=True, null=True)),
                ('substance_category', models.CharField(blank=True, choices=[('alcohol', 'Alcohol addiction'), ('drugs', 'Drug addiction'), ('nicotine', 'Nicotine dependence'), ('prescription_medication', 'Prescription medication misuse'), ('other', 'Other')], max_length=32)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('high_contrast_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
