# Generated by Django 5.2.16 on 2026-07-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('llm_risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('crisis_flag', models.BooleanField(default=False)),
                ('suggested_action', models.CharField(max_length=200)),
                ('model_name', models.CharField(default='claude-opus-5', max_length=64)),
                ('raw_response_json', models.JSONField(blank=True, null=True)),
                ('error_occurred', models.BooleanField(default=False)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_response', to='checkins.moodcheckin')),
            ],
        ),
    ]
