# Generated by Django 5.2.16 on 2026-07-25 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_date', models.DateField()),
                ('mood', models.CharField(choices=[('good', 'Feeling Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('craving', 'Craving')], max_length=16)),
                ('input_method', models.CharField(choices=[('tap', 'Tap'), ('voice', 'Voice')], max_length=8)),
                ('voice_transcript', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'local_date'], name='checkins_mo_user_id_1585ad_idx')],
            },
        ),
    ]
