# Generated by Django 5.2.16 on 2026-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_streakrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodcheckin',
            name='input_method',
            field=models.CharField(choices=[('tap', 'Tap'), ('voice', 'Voice'), ('call', 'Call')], max_length=8),
        ),
    ]
